services:
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - backend-web
      - api
    networks:
      - app_net
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - django_static:/var/www/static:ro

  backend-web:
    build: 
      context: .
      dockerfile: services/backend-web/Dockerfile
    env_file: .env
    depends_on:
      - db
      - redis
    expose:
      - "8001"
    command: ["/app/entrypoint_web.sh"]
    volumes:
      - django_static:/app/src/staticfiles
    networks:
      - app_net

  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    env_file: .env
    depends_on:
      - db
      - redis
    expose:
      - "8080"
    command: ["/app/entrypoint_api.sh"]
    networks:
      - app_net

  worker:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    env_file: .env
    depends_on:
      - db
      - redis
    command: ["celery", "-A", "app.celery_app:celery", "worker", "-l", "INFO"]
    networks:
      - app_net

  beat:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    env_file: .env
    depends_on:
      - db
      - redis
    command: ["celery", "-A", "app.celery_app:celery", "beat", "-l", "INFO"]
    networks:
      - app_net

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: csirt
      POSTGRES_USER: csirt
      POSTGRES_PASSWORD: csirt
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net

  redis:
    image: redis:7-alpine
    networks:
      - app_net

volumes:
  pgdata:
  django_static:

networks:
  app_net:
    name: csirt_app_net
    driver: bridge
